version: "3.7"
services:
  web:
    build: .
    volumes:
      - .:/home/app/robo_example_dev:z
    ports:
      - "80:80"
    depends_on:
      - db
    env_file:
      - 'docker/env.web'
  db:
    image: postgres:13.6
    ports:
      - "5432:5432"
    env_file:
      - 'docker/env.db'
